/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import static Jframe.DBConnection.con;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Date;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author diyaa
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Color mouseEnterColor = new Color(0,0,0);
    Color mouseExitColor = new Color(51,51,51);
    public Home() {
        initComponents();
        setStudentDetailsToTable();
        setBookDetailsToTable();
        setDataToCrads();
    }
    DefaultTableModel model;
    public void setStudentDetailsToTable(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","Ra@09091976");
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("select * from student_details");
             while (rs.next()){
                 String studentId = rs.getString("student_id");
                 String studentName = rs.getString("name");
                 String course = rs.getString("course");
                 String branch = rs.getString("branch");
                 Object[] obj ={studentId ,studentName,course,branch};
                 model =(DefaultTableModel) studenttable.getModel();
                 model.addRow(obj);
             }
        }catch(Exception e){
             e.printStackTrace();
        }
    }
    public void setBookDetailsToTable(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","Ra@09091976");
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("select * from book_details");
             while (rs.next()){
                 String bookId = rs.getString("book_id");
                 String bookName = rs.getString("book_name");
                 String author = rs.getString("author");
                 int quantity = rs.getInt("quantity");
                 Object[] obj ={bookId,bookName,author,quantity};
                 model =(DefaultTableModel) booktable.getModel();
                 model.addRow(obj);
             }
        }catch(Exception e){
             e.printStackTrace();
        }
    }
    public void setDataToCrads(){
        Statement st = null;
        ResultSet rs = null;
       long l = System.currentTimeMillis();  
       Date Todaysdate = new Date(l);
       
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","Ra@09091976");
             st= con.createStatement();
             rs = st.executeQuery("select * from book_details");
             rs.last();
             rs.getRow();
             lbl_book.setText(Integer.toString(rs.getRow()));
              rs = st.executeQuery("select * from student_details");
                rs.last();
             rs.getRow();
             lbl_student.setText(Integer.toString(rs.getRow()));
             rs = st.executeQuery("select * from issue_book_details where status ='"+"pending"+"'");
                rs.last();
             rs.getRow();
             lbl_issue.setText(Integer.toString(rs.getRow()));
             rs = st.executeQuery("select * from issue_book_details where due_date <'"+Todaysdate+"' and status = '"+"pending"+"'");
                rs.last();
             rs.getRow();
             lbl_defaulter.setText(Integer.toString(rs.getRow()));
        }catch(Exception e){
             e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1107 = new javax.swing.JPanel();
        jPanel1108 = new javax.swing.JPanel();
        lbl_book = new javax.swing.JLabel();
        jLabel1114 = new javax.swing.JLabel();
        jPanel1109 = new javax.swing.JPanel();
        lbl_issue = new javax.swing.JLabel();
        jLabel1116 = new javax.swing.JLabel();
        jPanel1111 = new javax.swing.JPanel();
        lbl_student = new javax.swing.JLabel();
        jLabel1119 = new javax.swing.JLabel();
        jLabel1121 = new javax.swing.JLabel();
        jLabel1122 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        booktable = new rojeru_san.complementos.RSTableMetro();
        jScrollPane3 = new javax.swing.JScrollPane();
        studenttable = new rojeru_san.complementos.RSTableMetro();
        jLabel1123 = new javax.swing.JLabel();
        jPanel1112 = new javax.swing.JPanel();
        lbl_defaulter = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1110 = new javax.swing.JPanel();
        jPanel1113 = new javax.swing.JPanel();
        jLabel1117 = new javax.swing.JLabel();
        jLabel1124 = new javax.swing.JLabel();
        jPanel1114 = new javax.swing.JPanel();
        jLabel1125 = new javax.swing.JLabel();
        jLabel1126 = new javax.swing.JLabel();
        jPanel1115 = new javax.swing.JPanel();
        jLabel1127 = new javax.swing.JLabel();
        jLabel1128 = new javax.swing.JLabel();
        jPanel1116 = new javax.swing.JPanel();
        jLabel1129 = new javax.swing.JLabel();
        jLabel1130 = new javax.swing.JLabel();
        jLabel1131 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        rSTableMetro4 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane5 = new javax.swing.JScrollPane();
        rSTableMetro5 = new rojeru_san.complementos.RSTableMetro();
        jLabel1132 = new javax.swing.JLabel();
        panelPieChart1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel555 = new javax.swing.JPanel();
        jPanel556 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel813 = new javax.swing.JPanel();
        jLabel818 = new javax.swing.JLabel();
        jPanel814 = new javax.swing.JPanel();
        jLabel819 = new javax.swing.JLabel();
        jPanel817 = new javax.swing.JPanel();
        jPanel818 = new javax.swing.JPanel();
        jLabel823 = new javax.swing.JLabel();
        jPanel819 = new javax.swing.JPanel();
        jPanel820 = new javax.swing.JPanel();
        jLabel825 = new javax.swing.JLabel();
        jLabel824 = new javax.swing.JLabel();
        jPanel815 = new javax.swing.JPanel();
        jLabel820 = new javax.swing.JLabel();
        jPanel821 = new javax.swing.JPanel();
        jLabel826 = new javax.swing.JLabel();
        jPanel823 = new javax.swing.JPanel();
        jLabel828 = new javax.swing.JLabel();
        jPanel824 = new javax.swing.JPanel();
        jLabel829 = new javax.swing.JLabel();
        jPanel825 = new javax.swing.JPanel();
        jLabel830 = new javax.swing.JLabel();
        jPanel826 = new javax.swing.JPanel();
        jLabel831 = new javax.swing.JLabel();
        jPanel827 = new javax.swing.JPanel();
        jLabel832 = new javax.swing.JLabel();
        jPanel828 = new javax.swing.JPanel();
        jLabel833 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1107.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1107.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1107.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1108.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1108.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 102, 51)));
        jPanel1108.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_book.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        lbl_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        lbl_book.setText(" 10");
        jPanel1108.add(lbl_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel1107.add(jPanel1108, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 200, 140));

        jLabel1114.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1114.setText("Issued Books");
        jPanel1107.add(jLabel1114, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        jPanel1109.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1109.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 102, 51)));
        jPanel1109.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_issue.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        lbl_issue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        lbl_issue.setText(" 10");
        jPanel1109.add(lbl_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jPanel1107.add(jPanel1109, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 200, 140));

        jLabel1116.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1116.setText("No. of Students");
        jPanel1107.add(jLabel1116, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jPanel1111.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1111.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(150, 0, 153)));
        jPanel1111.setLayout(null);

        lbl_student.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        lbl_student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        lbl_student.setText(" 10");
        lbl_student.setAutoscrolls(true);
        jPanel1111.add(lbl_student);
        lbl_student.setBounds(30, 40, 125, 69);

        jPanel1107.add(jPanel1111, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 200, 140));

        jLabel1119.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1119.setText("Defaulter List");
        jPanel1107.add(jLabel1119, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel1121.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1121.setText("No. of Books");
        jPanel1107.add(jLabel1121, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel1122.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1122.setText("Student Details");
        jPanel1107.add(jLabel1122, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        booktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "Author", "Qunatity"
            }
        ));
        booktable.setAlignmentX(40.0F);
        booktable.setColorBackgoundHead(new java.awt.Color(150, 0, 153));
        booktable.setColorBordeFilas(new java.awt.Color(150, 0, 153));
        booktable.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        booktable.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(booktable);

        jPanel1107.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 760, 160));

        studenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Name", "Course", "Branch"
            }
        ));
        studenttable.setAlignmentX(40.0F);
        studenttable.setColorBackgoundHead(new java.awt.Color(150, 0, 153));
        studenttable.setColorBordeFilas(new java.awt.Color(150, 0, 153));
        studenttable.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        studenttable.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(studenttable);

        jPanel1107.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 760, 160));

        jLabel1123.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1123.setText("Book Details");
        jPanel1107.add(jLabel1123, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jPanel1112.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1112.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(150, 0, 153)));
        jPanel1112.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_defaulter.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        lbl_defaulter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        lbl_defaulter.setText(" 10");
        jPanel1112.add(lbl_defaulter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jPanel1107.add(jPanel1112, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 200, 140));

        getContentPane().add(jPanel1107, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 1000, 630));

        panel1.setBackground(new java.awt.Color(150, 0, 153));
        panel1.setForeground(new java.awt.Color(150, 0, 153));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        panel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 5, 50));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Library Management System");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 240, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel2.setText("Welcome, Admin");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 220, -1));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 40, 30));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 70));

        jPanel1110.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1110.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1110.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1113.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1113.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 102, 51)));
        jPanel1113.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1117.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        jLabel1117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        jLabel1117.setText(" 10");
        jPanel1113.add(jLabel1117, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel1110.add(jPanel1113, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 200, 140));

        jLabel1124.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1124.setText("Issued Books");
        jPanel1110.add(jLabel1124, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        jPanel1114.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1114.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 102, 51)));
        jPanel1114.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1125.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        jLabel1125.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        jLabel1125.setText(" 10");
        jPanel1114.add(jLabel1125, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jPanel1110.add(jPanel1114, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 200, 140));

        jLabel1126.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1126.setText("No. of Students");
        jPanel1110.add(jLabel1126, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jPanel1115.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1115.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(150, 0, 153)));
        jPanel1115.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1127.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        jLabel1127.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        jLabel1127.setText(" 10");
        jLabel1127.setAutoscrolls(true);
        jPanel1115.add(jLabel1127, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jPanel1110.add(jPanel1115, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 200, 140));

        jLabel1128.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1128.setText("Defaulter List");
        jPanel1110.add(jLabel1128, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, -1));

        jPanel1116.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1116.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(150, 0, 153)));
        jPanel1116.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1129.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        jLabel1129.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        jLabel1129.setText(" 10");
        jPanel1116.add(jLabel1129, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jPanel1110.add(jPanel1116, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 200, 140));

        jLabel1130.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1130.setText("No. of Books");
        jPanel1110.add(jLabel1130, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel1131.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1131.setText("Student Details");
        jPanel1110.add(jLabel1131, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        rSTableMetro4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"331004", "Diya", "B.Tech", "IT"},
                {"331009", "Ayush", "B.Tech", "IT"},
                {"331012", "Harshak", "B.Tech", "IT"},
                {"331015", "Parth", "B.Tech", "IT"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Id", "Name", "Course", "Branch"
            }
        ));
        rSTableMetro4.setAlignmentX(40.0F);
        rSTableMetro4.setColorBackgoundHead(new java.awt.Color(150, 0, 153));
        rSTableMetro4.setColorBordeFilas(new java.awt.Color(150, 0, 153));
        rSTableMetro4.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rSTableMetro4.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(rSTableMetro4);

        jPanel1110.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 510, 160));

        rSTableMetro5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"331004", "Diya", "B.Tech", "IT"},
                {"331009", "Ayush", "B.Tech", "IT"},
                {"331012", "Harshak", "B.Tech", "IT"},
                {"331015", "Parth", "B.Tech", "IT"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Id", "Name", "Course", "Branch"
            }
        ));
        rSTableMetro5.setAlignmentX(40.0F);
        rSTableMetro5.setColorBackgoundHead(new java.awt.Color(150, 0, 153));
        rSTableMetro5.setColorBordeFilas(new java.awt.Color(150, 0, 153));
        rSTableMetro5.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        rSTableMetro5.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(rSTableMetro5);

        jPanel1110.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 510, 160));

        jLabel1132.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1132.setText("Book Details");
        jPanel1110.add(jLabel1132, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        panelPieChart1.setLayout(new java.awt.BorderLayout());
        jPanel1110.add(panelPieChart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 370, 260));

        getContentPane().add(jPanel1110, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 980, 630));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel555.setBackground(new java.awt.Color(51, 51, 51));
        jPanel555.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel556.setBackground(new java.awt.Color(255, 102, 51));
        jPanel556.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel6.setText("   Home Page");
        jPanel556.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel555.add(jPanel556, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 50));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        jLabel15.setText("  LMS Dashboard");
        jPanel555.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(jPanel555, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 50));

        jPanel813.setBackground(new java.awt.Color(255, 102, 51));
        jPanel813.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel818.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel818.setForeground(new java.awt.Color(255, 255, 255));
        jLabel818.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel818.setText("   Home Page");
        jPanel813.add(jLabel818, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel814.setBackground(new java.awt.Color(255, 102, 51));
        jPanel814.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel819.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel819.setForeground(new java.awt.Color(255, 255, 255));
        jLabel819.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel819.setText("   Home Page");
        jPanel814.add(jLabel819, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel813.add(jPanel814, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 50));

        jPanel817.setBackground(new java.awt.Color(255, 102, 51));
        jPanel817.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel818.setBackground(new java.awt.Color(255, 102, 51));
        jPanel818.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel823.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel823.setForeground(new java.awt.Color(255, 255, 255));
        jLabel823.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel823.setText("   Home Page");
        jPanel818.add(jLabel823, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel817.add(jPanel818, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 50));

        jPanel819.setBackground(new java.awt.Color(255, 102, 51));
        jPanel819.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel820.setBackground(new java.awt.Color(255, 102, 51));
        jPanel820.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel825.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel825.setForeground(new java.awt.Color(255, 255, 255));
        jLabel825.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel825.setText("   Home Page");
        jPanel820.add(jLabel825, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel819.add(jPanel820, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 50));

        jPanel817.add(jPanel819, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 50));

        jPanel813.add(jPanel817, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 50));

        jPanel1.add(jPanel813, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 50));

        jLabel824.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel824.setForeground(new java.awt.Color(255, 255, 255));
        jLabel824.setText("Features");
        jPanel1.add(jLabel824, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jPanel815.setBackground(new java.awt.Color(51, 51, 51));
        jPanel815.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel815MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel815MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel815MouseExited(evt);
            }
        });

        jLabel820.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel820.setForeground(new java.awt.Color(255, 255, 255));
        jLabel820.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        jLabel820.setText("   Manage Students");

        javax.swing.GroupLayout jPanel815Layout = new javax.swing.GroupLayout(jPanel815);
        jPanel815.setLayout(jPanel815Layout);
        jPanel815Layout.setHorizontalGroup(
            jPanel815Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel815Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel820)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel815Layout.setVerticalGroup(
            jPanel815Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel815Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel820)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel815, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 50));

        jPanel821.setBackground(new java.awt.Color(51, 51, 51));
        jPanel821.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel821MouseExited(evt);
            }
        });

        jLabel826.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel826.setForeground(new java.awt.Color(255, 255, 255));
        jLabel826.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel826.setText("   Manage Books");
        jLabel826.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel826MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel826MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel821Layout = new javax.swing.GroupLayout(jPanel821);
        jPanel821.setLayout(jPanel821Layout);
        jPanel821Layout.setHorizontalGroup(
            jPanel821Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel821Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel826)
                .addGap(43, 43, 43))
        );
        jPanel821Layout.setVerticalGroup(
            jPanel821Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel821Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel826)
                .addGap(84, 84, 84))
        );

        jPanel1.add(jPanel821, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 50));

        jPanel823.setBackground(new java.awt.Color(51, 51, 51));

        jLabel828.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel828.setForeground(new java.awt.Color(255, 255, 255));
        jLabel828.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        jLabel828.setText("   Return Books");
        jLabel828.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel828MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel828MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel828MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel823Layout = new javax.swing.GroupLayout(jPanel823);
        jPanel823.setLayout(jPanel823Layout);
        jPanel823Layout.setHorizontalGroup(
            jPanel823Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel823Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel828)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel823Layout.setVerticalGroup(
            jPanel823Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel823Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel828)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel823, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 220, 50));

        jPanel824.setBackground(new java.awt.Color(51, 51, 51));
        jPanel824.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel824MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel824MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel824MouseExited(evt);
            }
        });

        jLabel829.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel829.setForeground(new java.awt.Color(255, 255, 255));
        jLabel829.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        jLabel829.setText("   Issue Books");

        javax.swing.GroupLayout jPanel824Layout = new javax.swing.GroupLayout(jPanel824);
        jPanel824.setLayout(jPanel824Layout);
        jPanel824Layout.setHorizontalGroup(
            jPanel824Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel824Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel829)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel824Layout.setVerticalGroup(
            jPanel824Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel824Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel829)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel824, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 50));

        jPanel825.setBackground(new java.awt.Color(150, 0, 153));

        jLabel830.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel830.setForeground(new java.awt.Color(255, 255, 255));
        jLabel830.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        jLabel830.setText("  Logout");

        javax.swing.GroupLayout jPanel825Layout = new javax.swing.GroupLayout(jPanel825);
        jPanel825.setLayout(jPanel825Layout);
        jPanel825Layout.setHorizontalGroup(
            jPanel825Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel825Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel830)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel825Layout.setVerticalGroup(
            jPanel825Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel825Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel830)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel825, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 220, 50));

        jPanel826.setBackground(new java.awt.Color(51, 51, 51));

        jLabel831.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel831.setForeground(new java.awt.Color(255, 255, 255));
        jLabel831.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Books_26px.png"))); // NOI18N
        jLabel831.setText("   View Issue Books");
        jLabel831.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel831MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel831MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel831MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel826Layout = new javax.swing.GroupLayout(jPanel826);
        jPanel826.setLayout(jPanel826Layout);
        jPanel826Layout.setHorizontalGroup(
            jPanel826Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel826Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel831)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel826Layout.setVerticalGroup(
            jPanel826Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel826Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel831)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel826, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 220, 50));

        jPanel827.setBackground(new java.awt.Color(51, 51, 51));
        jPanel827.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel827MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel827MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel827MouseExited(evt);
            }
        });

        jLabel832.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel832.setForeground(new java.awt.Color(255, 255, 255));
        jLabel832.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        jLabel832.setText("   View Records");

        javax.swing.GroupLayout jPanel827Layout = new javax.swing.GroupLayout(jPanel827);
        jPanel827.setLayout(jPanel827Layout);
        jPanel827Layout.setHorizontalGroup(
            jPanel827Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel827Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel832)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel827Layout.setVerticalGroup(
            jPanel827Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel827Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel832)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel827, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 220, 50));

        jPanel828.setBackground(new java.awt.Color(51, 51, 51));

        jLabel833.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel833.setForeground(new java.awt.Color(255, 255, 255));
        jLabel833.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        jLabel833.setText("   Defaulter List");
        jLabel833.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel833MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel833MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel833MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel828Layout = new javax.swing.GroupLayout(jPanel828);
        jPanel828.setLayout(jPanel828Layout);
        jPanel828Layout.setHorizontalGroup(
            jPanel828Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel828Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel833)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel828Layout.setVerticalGroup(
            jPanel828Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel828Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel833)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel828, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel826MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel826MouseClicked
        ManageBooks MB = new ManageBooks();
        MB.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel826MouseClicked

    private void jLabel826MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel826MouseEntered
       jPanel821.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel826MouseEntered

    private void jPanel821MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel821MouseExited
      jPanel821.setBackground(mouseExitColor);
    }//GEN-LAST:event_jPanel821MouseExited

    private void jPanel815MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel815MouseEntered
        jPanel815.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jPanel815MouseEntered

    private void jPanel815MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel815MouseExited
       jPanel815.setBackground(mouseExitColor);
    }//GEN-LAST:event_jPanel815MouseExited

    private void jPanel815MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel815MouseClicked
        ManageStudents MS = new ManageStudents();
        MS.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel815MouseClicked

    private void jPanel824MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel824MouseClicked
       IssueBook IB = new IssueBook();
        IB.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel824MouseClicked

    private void jPanel824MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel824MouseEntered
          jPanel824.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jPanel824MouseEntered

    private void jPanel824MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel824MouseExited
        jPanel824.setBackground(mouseExitColor);
    }//GEN-LAST:event_jPanel824MouseExited

    private void jLabel828MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel828MouseClicked
         ReturnBook RB = new ReturnBook();
        RB.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel828MouseClicked

    private void jLabel828MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel828MouseEntered
      jPanel823.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel828MouseEntered

    private void jLabel828MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel828MouseExited
       jPanel823.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel828MouseExited

    private void jPanel827MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel827MouseClicked
       viewAllRecord VR = new viewAllRecord();
        VR.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel827MouseClicked

    private void jPanel827MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel827MouseEntered
       jPanel827.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jPanel827MouseEntered

    private void jPanel827MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel827MouseExited
        jPanel827.setBackground(mouseExitColor);
    }//GEN-LAST:event_jPanel827MouseExited

    private void jLabel831MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel831MouseClicked
      IssueBookDetails IR = new IssueBookDetails();
        IR.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel831MouseClicked

    private void jLabel831MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel831MouseEntered
      jPanel826.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel831MouseEntered

    private void jLabel831MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel831MouseExited
       jPanel826.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel831MouseExited

    private void jLabel833MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel833MouseClicked
       defaulterList DL = new defaulterList();
        DL.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel833MouseClicked

    private void jLabel833MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel833MouseEntered
       jPanel828.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel833MouseEntered

    private void jLabel833MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel833MouseExited
          jPanel828.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel833MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro booktable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1114;
    private javax.swing.JLabel jLabel1116;
    private javax.swing.JLabel jLabel1117;
    private javax.swing.JLabel jLabel1119;
    private javax.swing.JLabel jLabel1121;
    private javax.swing.JLabel jLabel1122;
    private javax.swing.JLabel jLabel1123;
    private javax.swing.JLabel jLabel1124;
    private javax.swing.JLabel jLabel1125;
    private javax.swing.JLabel jLabel1126;
    private javax.swing.JLabel jLabel1127;
    private javax.swing.JLabel jLabel1128;
    private javax.swing.JLabel jLabel1129;
    private javax.swing.JLabel jLabel1130;
    private javax.swing.JLabel jLabel1131;
    private javax.swing.JLabel jLabel1132;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel818;
    private javax.swing.JLabel jLabel819;
    private javax.swing.JLabel jLabel820;
    private javax.swing.JLabel jLabel823;
    private javax.swing.JLabel jLabel824;
    private javax.swing.JLabel jLabel825;
    private javax.swing.JLabel jLabel826;
    private javax.swing.JLabel jLabel828;
    private javax.swing.JLabel jLabel829;
    private javax.swing.JLabel jLabel830;
    private javax.swing.JLabel jLabel831;
    private javax.swing.JLabel jLabel832;
    private javax.swing.JLabel jLabel833;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1107;
    private javax.swing.JPanel jPanel1108;
    private javax.swing.JPanel jPanel1109;
    private javax.swing.JPanel jPanel1110;
    private javax.swing.JPanel jPanel1111;
    private javax.swing.JPanel jPanel1112;
    private javax.swing.JPanel jPanel1113;
    private javax.swing.JPanel jPanel1114;
    private javax.swing.JPanel jPanel1115;
    private javax.swing.JPanel jPanel1116;
    private javax.swing.JPanel jPanel555;
    private javax.swing.JPanel jPanel556;
    private javax.swing.JPanel jPanel813;
    private javax.swing.JPanel jPanel814;
    private javax.swing.JPanel jPanel815;
    private javax.swing.JPanel jPanel817;
    private javax.swing.JPanel jPanel818;
    private javax.swing.JPanel jPanel819;
    private javax.swing.JPanel jPanel820;
    private javax.swing.JPanel jPanel821;
    private javax.swing.JPanel jPanel823;
    private javax.swing.JPanel jPanel824;
    private javax.swing.JPanel jPanel825;
    private javax.swing.JPanel jPanel826;
    private javax.swing.JPanel jPanel827;
    private javax.swing.JPanel jPanel828;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbl_book;
    private javax.swing.JLabel lbl_defaulter;
    private javax.swing.JLabel lbl_issue;
    private javax.swing.JLabel lbl_student;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JPanel panelPieChart1;
    private rojeru_san.complementos.RSTableMetro rSTableMetro4;
    private rojeru_san.complementos.RSTableMetro rSTableMetro5;
    private rojeru_san.complementos.RSTableMetro studenttable;
    // End of variables declaration//GEN-END:variables
}
